@minimalapi_HostAddress = http://localhost:5151

GET {{minimalapi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET http://localhost:5151/message/world


###

PATCH http://localhost:5151/test
Content-Length: 5
Tus-Resumable: 1.0.0
Hello

###

GET http://localhost:5151/test